name: Format

on:
  workflow_call:
    inputs:
      command:
        description: 'The package.json script name which will be called via "pnpm run <command>"'
        default: "format"
        required: false
        type: string

jobs:
  format:
    # if: github.repository_owner == 'astrolicious'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run ${{ inputs.command }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_user_name: houstonlicious
          commit_user_email: houstonlicious@astro.licius
          commit_author: ${{ github.event.commits[0].author.name }} <${{ github.actor }}@users.noreply.github.com>
